"""Set S3 path constants."""
BUCKET = "twitter-project-daromi"
PREFIX_RAW = "data/raw/test"
PREFIX_CLEAN_UNGRUOPED = "data/clean/ungrouped"
GLUE_DATABASE = "tweet_project"
DATABASE_TABLE = "tweets"
PATH_TAGS_ECONOMY = "/home/ec2-user/lambdas/app/economic_tags.txt"
PATH_TAGS_UNCERTANTY = "/home/ec2-user/lambdas/tags_economia.txt"
PATH_STOP_WORDS = "/home/ec2-user/lambdas/app/stopwords-es.txt"
PATH_USER_LIST = "/home/ec2-user/lambdas/app/user_list.txt"
